### ISSUE TITLE
have to click 'signout' twice to get signed out

### ISSUE THREAD

**Issue by acandael** [nbudin/devise_cas_authenticatable#113]
Hi,

I,m not sure if this is a bug, or if I configured something wrong. But when I click the 'signout' link in my application the browser says it's connecting but seems to hang. Only when I click 'signout' a second time then I get signed out.

Does someone recognizes this issue?

My repository is at:

https://github.com/acandael/tracker

thanks for your help,

Anthony

**Comment by nbudin** [comment]
My first thought would be that you should be setting `cas_base_url` in the `config/initializers/devise.rb` to `"https://login.ugent.be"`.  Setting only the login and serviceValidate URLs seems like it would be likely to cause problems.

**Comment by acandael** [comment]
Hi nbudin, 

Sorry for my late response (out of office). Setting cas_base_url fixed the problem, thanks a lot.

greetings,

Anthony

**Comment by nbudin** [comment]
Great, glad to hear it!
