### ISSUE TITLE
undefined method `mounted_helpers'

### ISSUE THREAD

**Issue by medexdev** [nbudin/devise_cas_authenticatable#114]
I'm running rails 3.0.20, devise 1.5.4 and devise_cas_authenticatable 1.7.0. I'm getting "undefined method `mounted_helpers` exception. Here's complete stacktraces.

/usr/local/lib/ruby/gems/1.9.1/gems/devise_cas_authenticatable-1.7.0/lib/devise_cas_authenticatable/cas_action_url_factory_base.rb:8:in `block in prepare_class'
/usr/local/lib/ruby/gems/1.9.1/gems/devise_cas_authenticatable-1.7.0/lib/devise_cas_authenticatable/cas_action_url_factory_base.rb:6:in `initialize'
/usr/local/lib/ruby/gems/1.9.1/gems/devise_cas_authenticatable-1.7.0/lib/devise_cas_authenticatable/cas_action_url_factory_base.rb:6:in `new'
/usr/local/lib/ruby/gems/1.9.1/gems/devise_cas_authenticatable-1.7.0/lib/devise_cas_authenticatable/cas_action_url_factory_base.rb:6:in `prepare_class'
/usr/local/lib/ruby/gems/1.9.1/gems/devise_cas_authenticatable-1.7.0/lib/devise_cas_authenticatable.rb:120:in `cas_action_url_factory_class'
/usr/local/lib/ruby/gems/1.9.1/gems/devise_cas_authenticatable-1.7.0/lib/devise_cas_authenticatable.rb:116:in `cas_action_url'
/usr/local/lib/ruby/gems/1.9.1/gems/devise_cas_authenticatable-1.7.0/lib/devise_cas_authenticatable.rb:107:in `cas_service_url'
/usr/local/lib/ruby/gems/1.9.1/gems/devise_cas_authenticatable-1.7.0/app/controllers/devise/cas_sessions_controller.rb:74:in `cas_login_url'
/usr/local/lib/ruby/gems/1.9.1/gems/devise_cas_authenticatable-1.7.0/app/controllers/devise/cas_sessions_controller.rb:11:in `new'

If I comment out the following line (line #8) in lib/devise_cas_authenticatable/cas_action_url_factory_base.rb, it works fine.

        include Rails.application.routes.mounted_helpers if Rails.application.routes.try(:mounted_helpers)

**Comment by nbudin** [comment]
Hmm, interesting.  Could you try changing the `try` to `respond_to?` and see if that also fixes it?

**Comment by medexdev** [comment]
yes. if i change it to respond_to?, it works. thanks.

**Comment by nbudin** [comment]
OK, great.  I'll make that change in the gem itself and push a new version.

**Comment by nbudin** [comment]
This fix is now out in the newly-released version 1.7.1.
