### ISSUE TITLE
Using Gateway Filter

### ISSUE THREAD

**Issue by chap** [nbudin/devise_cas_authenticatable#116]
Anybody have luck using [rubycas-client's Gatewaying feature](https://github.com/rubycas/rubycas-client#gatewayed-ie-optional-authentication)?

These don't work:
```
before_filter CASClient::Frameworks::Rails::GatewayFilter
>> Cannot use the CASClient filter because it has not yet been configured.
```

```
before_filter Devise.cas_client::Frameworks::Rails::GatewayFilter
>> #<CASClient::Client: ... is not a class/module
```

**Comment by nbudin** [comment]
That feature is an extension of the rubycas-client Filter feature, which is a different authentication solution (separate from Devise).  It may be possible to do a similar thing here by manually implementing support for gatewaying in a similar way to how rubycas-client does it, but I'm not entirely sure of the details.

A pull request would be welcome (and I really mean that, not in the usual "patches welcome" way)!

**Comment by chap** [comment]
Thanks for your thoughts @nbudin, we're still deciding how we're going to deal with this issue.

If we decide to implement this we'll definitely send a PR.
