### ISSUE TITLE
Use CAS together with password authentication

### ISSUE THREAD

**Issue by danmichaelson** [nbudin/devise_cas_authenticatable#117]
Sorry if this is obvious. Is it possible to provide standard Devise password authentication to most users, with a link to log in via CAS as an alternative?

**Comment by nbudin** [comment]
Yes, that should be possible.  Just include the database_authenticatable columns as well as the cas_authenticatable ones, and include both of those modules in your `devise` declaration at the top of your model.

**Comment by danmichaelson** [comment]
Thanks

**Comment by revgum** [comment]
@nbudin I'm curious if you have suggestions on how to get the routes to behave side-by-side? I feel like I'm missing something simple.. 

```
$ rails routes
ArgumentError: Invalid route name, already in use: 'new_user_session'
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here:
```

**Comment by nbudin** [comment]
@revgum Devise is correct: you can't have two separate sessions controllers for the same model.  But it should be possible for a single sessions controller to handle both CAS and passwords.

If using the built-in sessions controller from Devise doesn't work for your use case and you need a custom sessions controller in your app, you will have to make sure it handles both cases.
