### ISSUE TITLE
SAML support

### ISSUE THREAD

**Issue by dsusco** [nbudin/devise_cas_authenticatable#118]
My institution only passes extra attributes via CAS over the SAML protocol. This requires a POST request to be sent to a different validation URL along with an XML body containing the CAS ticket.

I added support for this to rack-cas (https://github.com/biola/rack-cas/blob/master/lib/rack-cas/saml_validation_response.rb#L60), but I'd like to be able to leverage devise and not an authentication solution that I rolled myself. In looking through the devise_cas_authenticatable code I'm at a loss as to where something similar would go. Any pointers/suggestions?

**Comment by nbudin** [comment]
I think the place for it would probably be in the rubycas-client gem.  devise_cas_authenticatable is mostly just glue to make that gem work with Devise, and all the actual communicating with the CAS server happens in that gem.  So if you can add support in there, I'll be happy to expose whatever config options you need here to make that work.

**Comment by nbudin** [comment]
Now that devise_cas_authenticatable uses rack-cas behind the scenes in 2.0.0, this should work!
