### ISSUE TITLE
Passing query params with the login

### ISSUE THREAD

**Issue by sjoconnor** [nbudin/devise_cas_authenticatable#119]
Is there anyway to pass query params through to the CAS server? We have scenarios where a user will receive an URI in an email that will include query params that we'll use if the user is logged in, or once the user logs in. The problem is the params are being lost once the user is redirected to the CAS server.

Or, is it possible to dynamically generate the login url?

**Comment by sjoconnor** [comment]
It looks like devise is storing the initial params in `session["user_return_to"]`. Devise's `after_sign_in_path_for` method seems to be being called twice during an authentication. The first time it's called `session["user_return_to"]` contains desired information, the second time it's called the session seems to have been cleared. Is this intended?

**Comment by medexdev** [comment]
i'm interested in this as well. any comment?

**Comment by medexdev** [comment]
This may be a hack. I added the following and now it redirects. In CasSessionsController,

  def new
    # save original return to path.
    session["orig_#{resource_name}_return_to"] = session["#{resource_name}_return_to"]
    redirect_to(cas_login_url)
  end

  def service
    # restore original return to.
    session["#{resource_name}_return_to"] = session["orig_#{resource_name}_return_to"]
    redirect_to after_sign_in_path_for(warden.authenticate!(:scope => resource_name))
  end

**Comment by nbudin** [comment]
@medexdev: That would certainly work.  I agree it's a little bit of a hack, but if you absolutely must have this work that's one way to do it.

I'd love to have a real fix for this, but I'm not sure I fully understand the issue.  Specifically, I don't know why `after_sign_in_path_for` would be called twice.  Could either you or @sjoconnor provide some tracebacks for where `after_sign_in_path_for` is being called?  Thanks!

**Comment by medexdev** [comment]
sorry for late response. I debug it and here's the call flow. Please note my bold statements. First, session['user_return_to'] gets set after ApplicationController#home call. Then after_sign_in_path_for is called after Devise::CasSessionsController#service call. Then after_sign_in_path_for is called again after ApplicationController#home call. So basically, service call is using after_sign_in_path_for which deletes the original return_to path. So when the Application#home calls again, it's nil. Let me know if you need anything else. Thanks for looking into this.

Started GET "/?link=300" for 127.0.0.1 at 2016-05-12 16:39:51 -0700
Processing by ApplicationController#home as HTML
  Parameters: {"link"=>"300"}
Completed 401 Unauthorized in 1ms

**>>> store_location (location: '/?link=300') (at this point, session['user_return_to'] = '/?link=300')**

Started GET "/users/sign_in" for 127.0.0.1 at 2016-05-12 16:41:11 -0700
Processing by Devise::CasSessionsController#new as HTML
Redirected to http://localhost:7000/login?service=http%3A%2F%2Flocalhost%3A4000%2Fusers%2Fservice
Completed 302 Found in 5ms (ActiveRecord: 0.0ms)

Started GET "/users/service?ticket=ST-14630965314531-yxuPJTdYM5hWjsYIZ54KyGo3Sbd0u5Lda5fcVOEN" for 127.0.0.1 at 2016-05-12 16:42:11 -0700
Processing by Devise::CasSessionsController#service as HTML
  Parameters: {"ticket"=>"ST-14630965314531-yxuPJTdYM5hWjsYIZ54KyGo3Sbd0u5Lda5fcVOEN"}
Using conditions {username => test69} to find the User

**>>> after_sign_in_path_for (session['user_return_to'] = '/?link=300'), but session['user_return_to'] got deleted by this call. so session['user_return_to'] becomes nil.**

Redirected to http://localhost:4000/?link=300
Completed 302 Found in 77560ms (ActiveRecord: 7.0ms)

Started GET "/?link=300" for 127.0.0.1 at 2016-05-12 16:43:29 -0700
Processing by ApplicationController#home as HTML
  Parameters: {"link"=>"300"}
  Rendered layouts/application.html.erb within layouts/application (591.1ms)
Completed 200 OK in 713ms (Views: 698.1ms | ActiveRecord: 3.0ms)

**after_sign_in_path_for (called from Devise::SessionsController#create, but session['user_return_to'] is now nil so it doesn't redirect to /?link=300. instead it got redirected to root path.)**
