### ISSUE TITLE
redirect to current page

### ISSUE THREAD

**Issue by medexdev** [nbudin/devise_cas_authenticatable#122]
Is there a way to redirect user to current page after sign in? Let's say if i'm trying to go to

http://www.yyy.com/zzz

first, it will redirect to cas server for login. after login, how can i get back to that url? currently, it just goes back to home page http://www.yyy.com

**Comment by nbudin** [comment]
Does the method described on this page work? https://github.com/plataformatec/devise/wiki/How-To:-redirect-to-a-specific-page-on-successful-sign-in

(Note that you'll have to use the "without OAuth" version, and probably also the last section about overriding the other methods to make `after_sign_in_path_for` work without needing an exact referer match.)

**Comment by medexdev** [comment]
Thanks. Actually, this can be done with the method i described in the other issue #119
