### ISSUE TITLE
net/telnet isn't bundled in Ruby 2.3

### ISSUE THREAD

**Issue by jamgregory** [nbudin/devise_cas_authenticatable#123]
According to the Ruby 2.3 release notes (https://github.com/ruby/ruby/blob/trunk/doc/NEWS-2.3.0), net/telnet isn't bundled in Ruby 2.3 any longer. We've just discovered this when updating a Ruby 2.3 project to use devise_cas_authenticatable 1.8.0.

Could the net/telnet gem be added as a dependency when installing devise_cas_authenticatable on Ruby 2.3 (and newer) please?

**Comment by nbudin** [comment]
I've done something better. :)

As far as I know there is no way to add a dependency only for some versions of Ruby, but net/telnet was never a super hard requirement to do what MemcacheChecker was trying to do - only a convenience.  The newly-released devise_cas_authenticatable 1.9.0 replaces net/telnet with socket and timeout, which are still present in Ruby 2.3.

**Comment by jamgregory** [comment]
Cheers @nbudin :+1:
