### ISSUE TITLE
ERROR: Installing devise_cas_authenticatable 1.9.0 (was 1.8.0) on Windows

### ISSUE THREAD

**Issue by francesco-loreti** [nbudin/devise_cas_authenticatable#124]
I use corretly 1.8.0 but now if I update with 1.9.0 I have this error(if I force 1.8.0 version I don't have any problem):
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `C:/Ruby22-64bit/bin/bundle update`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    NotImplementedError: symlink() function is unimplemented on this machine
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:385:in `symlink'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:385:in `block (2 levels) in extract_tar_gz'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/package/tar_reader.rb:64:in `each'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:362:in `block in extract_tar_gz'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:456:in `block in open_tar_gz'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:453:in `wrap'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:453:in `open_tar_gz'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:361:in `extract_tar_gz'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:342:in `block (2 levels) in extract_files'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/package/tar_reader.rb:64:in `each'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:339:in `block in extract_files'
      C:/Ruby22-64bit/lib/ruby/2.2.0/open-uri.rb:36:in `open'
      C:/Ruby22-64bit/lib/ruby/2.2.0/open-uri.rb:36:in `open'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/package/file_source.rb:29:in `with_read_io'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:336:in `extract_files'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:761:in `extract_files'
      C:/Ruby22-64bit/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:288:in `install'
      C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:143:in `block in install'
      C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/bundler-1.12.3/lib/bundler/rubygems_integration.rb:169:in `preserve_paths'
      C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:135:in `install'
      C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/bundler-1.12.3/lib/bundler/installer/gem_installer.rb:57:in `install'
      C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/bundler-1.12.3/lib/bundler/installer/gem_installer.rb:15:in `install_from_spec'
      C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/bundler-1.12.3/lib/bundler/installer/parallel_installer.rb:91:in `block in worker_pool'
      C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/bundler-1.12.3/lib/bundler/worker.rb:65:in `call'
      C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/bundler-1.12.3/lib/bundler/worker.rb:65:in `apply_func'
      C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/bundler-1.12.3/lib/bundler/worker.rb:60:in `block in process_queue'
      C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/bundler-1.12.3/lib/bundler/worker.rb:57:in `loop'
      C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/bundler-1.12.3/lib/bundler/worker.rb:57:in `process_queue'
      C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/bundler-1.12.3/lib/bundler/worker.rb:29:in `block (2 levels) in initialize'

Environment

  Bundler   1.12.3
  Rubygems  2.5.1
  Ruby      2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
  GEM_HOME  C:/Ruby22-64bit/lib/ruby/gems/2.2.0
  GEM_PATH  C:/Ruby22-64bit/lib/ruby/gems/2.2.0;C:/Users/Francesco/.gem/ruby/2.2.0
  Git       2.7.2.windows.1

      Bundler settings

  build.nokogiri
    Set for the current user (C:/Users/Francesco/.bundle/config): "--use-system-libraries"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by nbudin** [comment]
I think I accidentally checked in my Gemfile symlink.  I've just released 1.9.1, which should remove that. Sorry for the issue!
