### ISSUE TITLE
extra_attributes= method not getting called despite being defined

### ISSUE THREAD

**Issue by tubsandcans** [nbudin/devise_cas_authenticatable#126]
In my User model, I have:
```ruby
def cas_extra_attributes=(extra_attributes)
  puts "Inspecting extra attributes"
  extra_attributes.each do |name, value|
    puts name.to_sym
    puts value
  end
end
```
Authorization is currently working using
  config.cas_user_identifier = 'mail'
  config.cas_username_column = :email

I would also like to save the username returned by our cas server into the username column for the user model. Yet when I log in to the app, I don't see "inspecting extra attributes" in my app's log, which means cas_extra_attributes= is never getting called. What is going on here?

**Comment by nbudin** [comment]
Hmm.  That method should definitely at least be called, if it exists.  It's possible that `authenticate_with_cas_ticket` isn't quite reaching that point.  Is it printing out the "Using conditions ... to find the User" log message?

**Comment by tubsandcans** [comment]
It is printing out the 'Using conditions...' with {email => <email_address>} and successfully finds the user account of that email (assuming it exists). For now I'm just parsing the email address and generating a username from it. This is certainly not preferable to getting the official CAS username from the ticket.

I'm wondering if by specifying a `cas_user_identifier` and `cas_username_column` in the devise config that it skips the call to `cas_extra_attributes`
