### ISSUE TITLE
Undefined method destroy_session for Cache Store

### ISSUE THREAD

**Issue by tomascharad** [nbudin/devise_cas_authenticatable#137]
Hi @nbudin ,

I think since Rails 5, Cache store changed the method destroy_session for delete_session.

http://api.rubyonrails.org/v4.0.13/classes/ActionDispatch/Session/CacheStore.html#method-i-destroy_session

http://api.rubyonrails.org/v5.1.1/classes/ActionDispatch/Session/CacheStore.html#method-i-delete_session

https://github.com/nbudin/devise_cas_authenticatable/blob/8737a287f0078b7c02f2deba431ff5a78a2dc7f1/lib/devise_cas_authenticatable/single_sign_out.rb#L31

Could we update this?

**Comment by nbudin** [comment]
Looks right - thanks for letting me know!  I'll have it check which one it responds to, in order to maintain backwards compatibility.

**Comment by nbudin** [comment]
This is now fixed in version 1.10.1.

**Comment by tomascharad** [comment]
Many thanks!
