### ISSUE TITLE
ArgumentError - Unsafe redirect "https://<mysite>/login?service=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fservice", use :fallback_location to specify a fallback or :allow_other_host to redirect anyway.

### ISSUE THREAD

**Issue by francesco-loreti** [nbudin/devise_cas_authenticatable#146]
Rails 6.0.0.beta1
Processing by Devise::CasSessionsController#new as HTML
Redirected to
Error:
`ArgumentError - Unsafe redirect "https://<mysite>/login?service=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fservice", use :fallback_location to specify a fallback or :allow_other_host to redirect anyway.:`

After error, if I copy the URL in the browser, the procedure proceeds correctly and I am logged.

Documentation: [https://api.rubyonrails.org/classes/ActionController/Redirecting.html](https://api.rubyonrails.org/classes/ActionController/Redirecting.html)

**Comment by francesco-loreti** [comment]
No. I don't know if it's a device problem or cas device problem and where you can resolve.

**Comment by francesco-loreti** [comment]
Any news? I have this problem again with Rails 7.0.0.rc1

**Comment by francesco-loreti** [comment]
> > Any news? I have this problem again with Rails 7.0.0.rc1
> 
> Since you opened this issue, there's a pre-release version of `devise_cas_authenticatable` that dramatically simplifies the gem by making it a wrapper around the `rack-cas` middleware. If you haven't already, could you try upgrading to `devise_cas_authenticatable` version 2.0.0.alpha1 and let me know if it solves your problem?

I tried the new alpha version and, after having also integrated the rack-cas parameters indicated in the guide, it seems to work without generating an error during login. So it would look ok. I'm finishing fixing the project with Rails 7 so, in case I find errors, I will open a specific issue. For now, thank you for the support!

**Comment by nbudin** [comment]
Great, thank you for testing it!  If I don't hear from you in a few weeks, I'll assume things are going ok and possibly cut a real release of this version.  (I've been using it successfully in my own apps, but haven't had anyone else using it until now.)

**Comment by francesco-loreti** [comment]
> Great, thank you for testing it! If I don't hear from you in a few weeks, I'll assume things are going ok and possibly cut a real release of this version. (I've been using it successfully in my own apps, but haven't had anyone else using it until now.)

I am sorry about that. I use the old stable version in some projects and I am fine and with the arrival of Rails 7 probably also others who use the old version will have to switch to the new one especially if the system generates an error. Anyway I have not yet had the opportunity to try the logout but for the login everything is ok.

**Comment by nbudin** [comment]
2.0.0 is released, so that should solve this for everyone at this point!
