### ISSUE TITLE
Validate Ticket on every Request?

### ISSUE THREAD

**Issue by non1ckname** [nbudin/devise_cas_authenticatable#149]
Hey

Is it possible to validate the ticket/session on every web request the user does?
I have multiple Web-Apps that use devise_cas_authenticatable and a CAS Server for authentification.
If i logout myself on one App, the other Apps are still loged in. 

How can I tell the Apps to check there service_ticket on every web-request?

Thank you a lot!

**Comment by nbudin** [comment]
For solving the issue of signing yourself out on all apps, I don't recommend this approach.  Instead, I recommend implementing Single Sign-Out, which is a part of the CAS standard that will allow the CAS server to tell all other apps to sign out the user.

devise_cas_authenticatable supports single sign-out if you enable `config.cas_enable_single_sign_out = true` in your initializer.  To do this, you have to be using some kind of server-side persisted sessions, such as ActiveRecord session store or Redis session store.

Enabling single sign-out will also start putting the user's CAS ticket in the session, under `session['cas_last_valid_ticket']`.  If you really want to put a `before_action` in ApplicationController and revalidate that ticket with the server, you can do it.  I don't necessarily expect it would work with every CAS server, and it would also make every request slower and possible to fail if the CAS server doesn't respond in time or something.  So, as I said, I don't recommend that approach.
