### ISSUE TITLE
uninitialized constant Devise::Models::CasAuthenticatable

### ISSUE THREAD

**Issue by macmartine** [nbudin/devise_cas_authenticatable#15]
I'm adding devise_cas_authenticatable to my app that already has Devise wokring in it and I'm hitting a wall. I have followed the instructions several times. I'm getting this error:

```
uninitialized constant Devise::Models::CasAuthenticatable
```

in my devise model where I added devise :cas_authenticatable

```
class User < ActiveRecord::Base

belongs_to :business
accepts_nested_attributes_for :business

devise :registerable, :confirmable, :lockable,
  :recoverable, :rememberable, :trackable, :validatable, :cas_authenticatable
  # :database_authenticatable
end
```

Do you have any idea what would cause this? 

The gem is installed: Using devise_cas_authenticatable (1.0.0.alpha10)

**Comment by tomascharad** [comment]
Hi! I have the same problem! I have tried dozens of ways to fix this but no luck...

**Comment by tomascharad** [comment]
Could this issue be reopened?

**Comment by nbudin** [comment]
@tomascharad - That doesn't sound like the same issue to me.  The capitalization thing is probably significant.  Could you file a separate issue with that traceback, and also post a sample of your model code that triggers it?

**Comment by tomascharad** [comment]
@nbudin, thanks very much for checking it out. I already created a new issue. Please, let me know if you have any clue.
