### ISSUE TITLE
[question] Disable/enable cas create user

### ISSUE THREAD

**Issue by francesco-loreti** [nbudin/devise_cas_authenticatable#158]
Hello
In the gem 1 release there was the configuration parameter `config.cas_create_user = true / false`. 
In the second version of the gem, is there this parameter and what is the name?

Thanks for the reply.
Francesco

**Comment by nbudin** [comment]
Yes, this parameter hasn't changed since version 1.  It should still be possible to set it just as before.  The default is `true`.
