### ISSUE TITLE
Problem with "ticket" (undefined local variable or method `ticket')

### ISSUE THREAD

**Issue by erikm30** [nbudin/devise_cas_authenticatable#160]
From my CAS Server I get apparently a reply with a ticket in the form
xx-nnnn-nXxXnXnxXxxnXnxxXnxxXXXXxnx-xxx_xxxx_xxnn
which is then passed on as
/admin/login?ticket=xx-nnnn-nXxXnXnxXxxnXnxxXnxxXXXXxnx-xxx_xxxx_xxnn

Then I get
- Started GET "/admin/service
- Processing by Devise::CasSessionsController#service as HTML
- Using conditions {username => XXXXXX} to find the User
- Completed 500 Internal Server Error in 25ms (ActiveRecord: 6.3ms | Allocations: 9613)
- NameError (undefined local variable or method `ticket' for #<Devise::Strategies::CasAuthenticatable:0x000000000a02bd68>

Devise::CasSessionsControlker::Service is overridden, but is using the same code as the "original" class.
      redirect_to after_sign_in_path_for(warden.authenticate!(:scope => resource_name)) # usual SSO logic

Any idea

**Comment by erikm30** [comment]
Thanks a lot for the fast answer.
Setting `cas_enable_single_sign_out` to `false `indeed solved the issue!

**Comment by nbudin** [comment]
This is now fixed in 2.0.2!
