### ISSUE TITLE
Redirect Loop when Memcache down (using memcache as session store)

### ISSUE THREAD

**Issue by fabioperrella** [nbudin/devise_cas_authenticatable#89]
Hi,
when using memcache to store the session, if all memcache servers are down, when trying to access application, it raises a redirect loop error because gem redirects to CAS which redirects to application, then try to save session in memcache (which is down), so it fails, then redirects to CAS again until gets a redirect loop error.
Maybe it would be necessary to check if Rails.cache can write to cache, if not, raises an error

**Comment by adamel** [comment]
@nbudin please close this issue as the patch has been merged years ago.

**Comment by nbudin** [comment]
Thanks @adamel!  Good looking out.
