### ISSUE TITLE
uninitialized constant Devise::Models::CASAuthenticatable (NameError)

### ISSUE THREAD

**Issue by tomascharad** [nbudin/devise_cas_authenticatable#97]
Hi @nbudin,

As suggested I'm creating a new issue about the uninitialised constant:

Prior to this change I had mounted another project with devise_cas_authenticable (with ActiveRecord though) which was client of this CAS server on which I'm having problems. While setting it up I remember facing this exact same issue, but I cannot recall how I sorted it out. In the other hand, my ex-collegue which setted up this CAS server also setted up a cas client in another app on which was the User DB.

What we are doing now is moving the User DB to the CAS server to have everything more ordered, so what I did was to export/import the MongoDB DB into the cas server and copying the User and related model files with some minor changes but I haven't been able to get devise_cas_authenticable to run properly

My stacktrace is:

Tomass-MBP:TransitUC-SSO tomascharad$ rails server
=> Booting WEBrick
=> Rails 3.2.16 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/models.rb:88:in `const_get': uninitialized constant Devise::Models::CASAuthenticatable (NameError)
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/models.rb:88:in `block (2 levels) in devise'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/models.rb:87:in `each'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/models.rb:87:in `block in devise'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/models.rb:114:in `devise_modules_hook!'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/models.rb:84:in `devise'
	from /Users/tomascharad/Devapps/TransitUC-SSO/app/models/user.rb:15:in `<class:User>'
	from /Users/tomascharad/Devapps/TransitUC-SSO/app/models/user.rb:1:in `<top (required)>'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.16/lib/active_support/inflector/methods.rb:230:in `block in constantize'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.16/lib/active_support/inflector/methods.rb:229:in `each'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.16/lib/active_support/inflector/methods.rb:229:in `constantize'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise.rb:302:in `get'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/mapping.rb:80:in `to'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/mapping.rb:75:in `modules'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/mapping.rb:92:in `routes'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/mapping.rb:159:in `default_used_route'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/mapping.rb:69:in `initialize'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise.rb:336:in `new'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise.rb:336:in `add_mapping'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/rails/routes.rb:224:in `block in devise_for'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/rails/routes.rb:223:in `each'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/rails/routes.rb:223:in `devise_for'
	from /Users/tomascharad/Devapps/TransitUC-SSO/config/routes.rb:5:in `block in <top (required)>'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/actionpack-3.2.16/lib/action_dispatch/routing/route_set.rb:285:in `instance_exec'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/actionpack-3.2.16/lib/action_dispatch/routing/route_set.rb:285:in `eval_block'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/actionpack-3.2.16/lib/action_dispatch/routing/route_set.rb:263:in `draw'
	from /Users/tomascharad/Devapps/TransitUC-SSO/config/routes.rb:1:in `<top (required)>'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.16/lib/active_support/file_update_checker.rb:78:in `call'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.16/lib/active_support/file_update_checker.rb:78:in `execute'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/application/finisher.rb:66:in `block in <module:Finisher>'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/initializable.rb:30:in `run'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/initializable.rb:54:in `each'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/application.rb:136:in `initialize!'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /Users/tomascharad/Devapps/TransitUC-SSO/config/environment.rb:5:in `<top (required)>'
	from /Users/tomascharad/Devapps/TransitUC-SSO/config.ru:3:in `block in <main>'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
	from /Users/tomascharad/Devapps/TransitUC-SSO/config.ru:in `new'
	from /Users/tomascharad/Devapps/TransitUC-SSO/config.ru:in `<main>'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/builder.rb:40:in `eval'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/builder.rb:40:in `parse_file'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/server.rb:200:in `app'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/commands/server.rb:46:in `app'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/server.rb:304:in `wrapped_app'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.4.5/lib/rack/server.rb:254:in `start'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/commands/server.rb:70:in `start'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/commands.rb:55:in `block in <top (required)>'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/commands.rb:50:in `tap'
	from /Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/commands.rb:50:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

And my User model is the following:

class User
  include Mongoid::Document
  rolify

  ##########
  # DEVISE #
  ##########

  # Include the database authenticatable module (independently) to allow for the registration of the user models (just authentication is ).

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :omniauthable,
  # :database_authenticatable # Replaced by :cas_authenticatable
  devise :cas_authenticatable, :rememberable, :trackable, :validatable, :recoverable, :registerable, :authentication_keys => [:email]

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  validates_presence_of :email
  field :encrypted_password, :type => String, :default => ""
  validates_presence_of :encrypted_password

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  #####################
  # Accessible Fields #
  #####################

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :bus_company_id, :role_ids

  #############
  # Callbacks #
  #############

  before_save :update_bus_company_and_role

  ##################
  # NonAuth Fields #
  ##################

  field :name, :type => String
  validates_presence_of :name

  #############
  # Relations #
  #############

  has_and_belongs_to_many :roles, :inverse_of => nil
  belongs_to :bus_company
  # has_one :bus_status, dependent: :nullify, class_name: 'BusStatus', inverse_of: :user

  ###########
  # Indexes #
  ###########

  index({ email: 1 }, { unique: true, background: true })

  ###########
  # Methods #
  ###########

  # Returns the roles list on a humanized list
  def get_humanized_roles_list

    # Get the list of
    humanized_roles = self.roles.map do |role|
      role.human_attribute_value(:name)
    end

    # Return the string
    humanized_roles * ', '
  end

protected

  def update_bus_company_and_role
    if role_ids_changed?
      admin_id = Role.find_by(name: :admin).id
      bus_company_manager_id = Role.find_by(name: :bus_company_manager).id

      if self.role_ids.include? admin_id

        # Delete the bus_company_manager_id
        self.role_ids -= [bus_company_manager_id]

        # Delete the buscompany relation
        self.bus_company = nil

      end
    end
  end

end

**Comment by nbudin** [comment]
So looking at the last line of the traceback, it's pointing at this line in Devise's `lib/devise/models.rb` file:

```ruby
mod = Devise::Models.const_get(m.to_s.classify)
```

It seems that, somehow, `:cas_authenticatable.to_s.classify` is returning the string `"CASAuthenticatable"` in your app.  I've tried this myself in a stock Rails installation and for me it returns `CasAuthenticatable`, which would be what I'd expect.  Do you have any custom inflection configuration in your app that might cause this?

Also, if you paste `:cas_authenticatable.to_s.classify` into a Rails console in your app, what do you get back?

**Comment by tomascharad** [comment]
@nbudin Thank you very much for your response,

This is what I get from the console:

1.9.3-p551 :001 > :cas_authenticatable.to_s.classify
 => "CASAuthenticatable"

**Comment by tomascharad** [comment]
@nbudin I have changed my model to the following:

devise "CasAuthenticable", :rememberable, :trackable, :validatable, :recoverable, :registerable, :authentication_keys => [:email]

And now I get:

/Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/models.rb:88:in `const_get': uninitialized constant Devise::Models::CasAuthenticable (NameError)

**Comment by nbudin** [comment]
That's because you have a spelling error: it should be Authenticatable, not Authenticable.

**Comment by tomascharad** [comment]
Corrected it, but same issue... sorry about the misspelling

/Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/lib/devise/models.rb:88:in `const_get': uninitialized constant Devise::Models::CasAuthenticatable (NameError)

**Comment by nbudin** [comment]
OK, now that is getting bizarre.  As you can see in https://github.com/nbudin/devise_cas_authenticatable/blob/master/lib/devise_cas_authenticatable/model.rb, that is defined in the gem.

Could you double-check that your Gemfile includes devise_cas_authenticatable?  That's the only thing I can think of that might cause it not to be available at this point.

**Comment by tomascharad** [comment]
Yes I now is very rare... 

This is part of my gemfile:
gem 'mongoid'
gem 'rolify'
gem 'devise_cas_authenticatable'
gem 'devise'

and this is part of the output of bundle

Using devise 3.4.1
Using rubycas-client 2.3.9
Using devise_cas_authenticatable 1.3.7
Using jquery-rails 3.1.2
Using kgio 2.9.2
Using origin 1.1.

**Comment by nbudin** [comment]
OK, I am not sure what to do anymore to help you debug this issue.  Between the weird capitalization in the inflector and the inability to load that module, I think this has to be some bug in either your app or the Ruby setup you're running it on.  I do not believe this is a bug in the library itself.

Sorry, but I'm going to close this issue.  I don't think there's any more I can do for you.  If you do discover a bug in the library, please let me know.

**Comment by tomascharad** [comment]
Ok last check,

This is what I get when adding this line: require 'devise_cas_authenticatable/models' (extracted from the related issue) in the User model

/Users/tomascharad/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- devise_cas_authenticatable/models (LoadError)

**Comment by tomascharad** [comment]
Thanks very much though

**Comment by nbudin** [comment]
That should be "model", not "models".

**Comment by tomascharad** [comment]
Now it worked! Thanks very much!

**Comment by tomascharad** [comment]
Hi @nbudin 
The inflection issue might have been caused by the gem "casino" which defines the following:

ActiveSupport::Inflector.inflections do |inflect|
  inflect.acronym 'CAS'
  inflect.acronym 'CASino'
end

**Comment by nbudin** [comment]
Ah, yes, that makes sense.  That seems like possibly a dangerous thing for a gem to do in general; I wonder if it is perhaps worth asking them if they'd consider changing that.

**Comment by tomascharad** [comment]
Well thank you very much!
Do you think if this might be causing conflicts when calling :authenticate_user! ?
I'm obtaining 401 even when I have a CAS session active

**Comment by nbudin** [comment]
It could be.  It seems like mixing CASino and devise_cas_authenticatable within the same app is not safe to do.

If I may ask, why are you mixing these gems in the same app?  Since one of them is a CAS server and the other is effectively a CAS client, I'm not sure what the use case is.

**Comment by tomascharad** [comment]
We want to be able to manage our users in the same application that holds the Authentication logic for centralisation purposes.

The users used to be held on a separate db from another app. We now want that the CAS server holds the user table and that the administration of this users is done on the same app. That is why I have created a users controller which authenticates the users in order to check if they have the permission to manage other users.

What do you think about this?

**Comment by nbudin** [comment]
That seems reasonable, but it might be worth considering using some mechanism other than CAS to authenticate your users in Devise within the CAS server app.  For example, you could have it read the database table directly using database_authenticatable, and (possibly) use something like encryptable or whatever the modern equivalent of that is, to verify passwords using the mechanism CASino uses (if it's not bcrypt).  Doing things that way would avoid having CASino in the loop when doing a local login on the CAS server itself, which seems like it would be much more robust.  You'll still be able to have other apps authenticate to CASino even if you do things this way.

**Comment by tomascharad** [comment]
Thanks @nbudin, for your suggestion!

I think that using another method of authentication will not allow a simple path for our users to manage accounts from our dashboard (They would have to login twice in order to do so).

I think though that I'm very close to the solution of this problem. What method would you suggest me for debugging the authenticate_user! method?

**Comment by nbudin** [comment]
@tomascharad, I'm not really sure.  Sorry about that!

For what it's worth, the method I suggested is somewhat similar to what I actually do in [my own CAS server and user management app](https://github.com/nbudin/illyan).  In that app, I use Devise with database_authenticatable to log users in, and I've embedded Cassy as a CAS server, modified slightly to let it use Devise's own session and login screens rather than doing authentication itself.  In that way, users don't have to log in twice.

**Comment by tomascharad** [comment]
Thanks very much @nbudin!

I believe that would be a good way to solve the problem.
Anyway, the team decided to migrate the user administration to a separate app as you suggested.
We tried by forking CASino and removing the inflection but this caused some conflicts with some rake tasts.
I have let them know that their inflections were causing conflicts with you gem.

I really appreciate all of your time and patience!
